[tool.poetry]
name = "matrix-loading"
version = "0.1.0"
description = "Matrix Data Analysis for 42 School"
authors = ["Tatev <tatevyeghiazaryann5@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas = "*"
numpy = "*"
matplotlib = "*"
requests = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"